### PR TITLE
[DON'T MERGE] mGBA updates, Game Boy support

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
Let's wait for the next release. Making a PR just to aware people to not waste time merging & fixing.

```
< endrift > sergio-br2: don't merge yet, the cheats changed heavily last night and I haven't had time to test them yet
< endrift > also game boy support is lackluster
< endrift > needs a lot of work
```

I tested it only on Linux.

### CODE REVIEW

**Comment by tony971** [comment]
Now that 0.4.1 is out on upstream mGBA, can this be rebased and merged?

**Comment by sergiobenrocha2** [comment]
Nope.

**Comment by sergiobenrocha2** [comment]
Wait, you mean rebase with 0.4.1 changes, in another branch? It'll need changes in other repos too, libretro-super I think.

**Comment by twinaphex** [comment]
Can we merge this thing already now or how long is this going to take?

You havent even taken care of the merge conflict and yet this thing has stayed in here for months.

Must I absolutely do everything here by myself?

**Comment by fr500** [comment]
He is only honoring the author's wishes by not merging till the new features are ready

**Comment by twinaphex** [comment]
That was May 8, and honestly, we need to stay up to date. I am not going to stay months behind on some 'official' version, that might be very convenient for him, but not so convenient for us.

**Comment by sergiobenrocha2** [comment]
There's no merge conflict, I fix that every time I merge it, I can say it's working fine at least on Linux.

Endrift said to not merge it, but if you are in the rush to merge, then do that.

**Comment by twinaphex** [comment]
In a rush to merge? this goddamn thing has been in here since May. You call this a 'rush', being months and months out of date?

**Comment by sergiobenrocha2** [comment]
Merge it then I guess.

**Comment by sergiobenrocha2** [comment]
Eh, I need to rebase against the new commits from the fork right? I forgot that.

**Comment by twinaphex** [comment]
So what do we do here? Just make a new fork and transfer the static Makefile over?

**Comment by sergiobenrocha2** [comment]
No, I'll try to sherry pick that cheevos commits

**Comment by sergiobenrocha2** [comment]
I think it's better wait endrift implement cheevos, then we rollback some commits in master to be able merge this PR

```
<endrift> sergio-br2: there's no way you're going to be able to merge this yourself
<endrift> the infrastructure has changed too much
<endrift> with GB support
<endrift> this would break horribly
<sergio-br2> :/
<sergio-br2> so better you implement it yourself?
<endrift> yes
```

**Comment by twinaphex** [comment]
Alright, lets close this then.

**Pull request closed without merging**
