### PR TITLE
mGBA updates, Game Boy support [again]

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
endrift will release 0.5 in the next few days, so let's make a beta release to receive feedback / bug reports as much as possible

I tested it only on Linux, it's working great!

@twinaphex please rollback to 851dbb1, endrift backported cheevos

### CODE REVIEW

**Comment by endrift** [comment]
Please note that this doesn't support achievements or memory maps in the GB core, only in the GBA core. I'm assuming most people will use other libretro cores for GB, so it's not a big deal that it's missing for now, but I do want to add it in the future.

**Comment by fr500** [comment]
@endrift thanks for the heads up!
@sergiobenrocha2 you mean force push to that commit, then merge?

**Comment by fr500** [comment]
I guess the only thing we are missing is 
https://github.com/libretro/mgba/commit/b4f9e8c919fad191ef9232d468427f93d4d9c2fb

**Comment by sergiobenrocha2** [comment]
Yup, revert & force push, then merge.

I already backported that rpi3 commit.

**Comment by sergiobenrocha2** [comment]
Any problem with this PR?

**Pull request merged**
