### PR TITLE
mGBA-libretro: Update version number to 0.8.4 stable

### PR DESCRIPTION
**Pull request by Ntemis**

### CODE REVIEW

**Comment by Ntemis** [comment]
Dont merge yet

**Comment by twinaphex** [comment]
@endrift Over to you for your approval.

**Comment by endrift** [comment]
Well, there are some merge conflicts that got committed (probably why @Ntemis said "don't merge yet"), but the non-libretro parts don't look like there were any conflicts.

**Comment by Ntemis** [comment]
Yeah ctl+f searching for <<< played a trick on me somehow.
Will fix tomorrow if i get the time.Thanks for the patience

**Comment by twinaphex** [comment]
Hi @Ntemis , just checking up on how things are going with this PR. Thanks.

**Comment by Ntemis** [comment]
Shoot i forgot all about it. I will have it done tonight.

**Comment by endrift** [comment]
Still doesn't seem to build. Not sure there's much reason to keep the conflicted code commented out, fwiw.

**Comment by Ntemis** [comment]
I left it there for the next one that tries to update  so to know the diverse.
As for those warnings i only find this line missing 
https://github.com/mgba-emu/mgba/blob/0.8/src/platform/libretro/libretro.c#L569
everything else look in order.
Dont know PS2 compilers and have zero interest in fixing that target.
I can close this and the next one can follow this to the end

**Comment by endrift** [comment]
The error is `src/platform/libretro/libretro.c:1140:1: unterminated #else` so I'm not sure it affects PS2 only.

**Comment by Ntemis** [comment]
oh let me have a look then , thanks didnt noticed and am sure i saw only warnings

**Comment by Ntemis** [comment]
It was pointing to the wrong line but i think i got it :)

**Comment by endrift** [comment]
LGTM

**Pull request merged**
