### PR TITLE
Fix #213

### LINKED ISSUE #213: PS3 - Since commit 2a221b3 a segmentation fault appeared
.... when you try to start a rom. I'm looking for solve it.

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by endrift** [comment]
What is this? The indentation is wrong, the typedefs are...very strange. Did you copy-paste this from some site?

**Comment by crystalct** [comment]
From ppu_intrinsics.h of SDk Sony. Just a bit arranged.

**Comment by endrift** [comment]
I absolutely cannot accept code from the SDK; it's violating copyrights just to post it here.

**Comment by crystalct** [comment]
Every include inside a `#if defined (__CELLOS_LV2__)` is taken from that SDK.... all code working for PS3 of retroarch and cores is in that way....

**Comment by endrift** [comment]
I hate to break it to you but that's a huge problem and means the compiled cores are illegal.

**Comment by crystalct** [comment]
For example, take a look here:
```
Makefile.libretro:      CC = $(CELL_SDK)/host-win32/sn/bin/ps3ppusnc.exe
Makefile.libretro:      AR = $(CELL_SDK)/host-win32/sn/bin/ps3snarl.exe
Makefile.libretro:      CC = $(CELL_SDK)/host-win32/ppu/bin/ppu-lv2-gcc.exe
Makefile.libretro:      AR = $(CELL_SDK)/host-win32/ppu/bin/ppu-lv2-ar.exe
```
Clear references to Sony SDK and have been there for years.....

**Comment by endrift** [comment]
It's pretty well known that the project uses illegally obtained SDKs, and the project management just Does Not Care. However, code actually taken out of the SDK (as opposed to just a #include statement) is far more tainting and I cannot accept in any way.

**Comment by endrift** [comment]
It turns out that specific file _also_ appears in the open source distribution of gcc (e.g. https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=gcc/config/rs6000/ppu_intrinsics.h;h=ff6a1acefd71740026e0479536dfa096941fa272;hb=b1a2242e24fe984711214b7546cb993cfe45ace8#l273), however the SDK itself is being distributed illegally, which is definitely a problem.

**Comment by crystalct** [comment]
So?

**Comment by crystalct** [comment]
I could use __lhbrx, __lwbrx, __ldbrx; __sthbrx (etc etc),  Macros well documented in many IBM public documents....

**Comment by twinaphex** [comment]
@endrift You were given admin privileges over this fork, all you have to do is to accept it (there's a mail in your inbox). You can decide to merge or reject whatever you want.

**Comment by twinaphex** [comment]
Actually, let's rather close this. We have made very sure that there is no copyrighted code/material inside RetroArch or any of the cores at all, and we'd like to keep it that way. Even if in this case that file comes from GCC proper, you still have to be more careful than that. Come up with a solution instead that is platform-agnostic and can work on any PowerPC-centric CPU, like the IBM public files. We will close this meanwhile.

**Comment by twinaphex** [comment]
To reiterate, the platforms we support for the consoles are all based on homebrew SDKs - 3DS (libctr) , WiiU , Gamecube/Wii (libogc), Nintendo Switch (libnx), PlayStation2, PlayStation Portable, PlayStation Vita, and PlayStation3 with PSL1GHT. On top of that, we support Microsoft Xbox One through Windows UWP. Anything else that exists outside of that is unofficial and in most cases not even developed by us.

**Comment by twinaphex** [comment]
@crystalct is also wrong in his assertion. We have NOT included copyrighted code into any of our cores.

**Comment by crystalct** [comment]
From libffmpeg->libavutil ->ppc->intreadwrite.h

```
/*
 * Copyright (c) 2008 Mans Rullgard <mans@mansr.com>
 *
 * This file is part of FFmpeg.
 *
 * FFmpeg is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * FFmpeg is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with FFmpeg; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef AVUTIL_PPC_INTREADWRITE_H
#define AVUTIL_PPC_INTREADWRITE_H

#include <stdint.h>
#include "config.h"

/*
 * -O0 would compile the packed struct version, which is used by
 * default, in an overly verbose fashion, so we override it here.
 */
#if HAVE_BIGENDIAN
#define AV_RB64(p) (*(const uint64_t *)(p))
#define AV_WB64(p, v) (*(uint64_t *)(p) = (v))

#else
#define AV_RL64(p) (*(const uint64_t *)(p))
#define AV_WL64(p, v) (*(uint64_t *)(p) = (v))

#endif

#if HAVE_XFORM_ASM

#if HAVE_BIGENDIAN
#define AV_RL16 av_read_bswap16
#define AV_WL16 av_write_bswap16
#define AV_RL32 av_read_bswap32
#define AV_WL32 av_write_bswap32
#define AV_RL64 av_read_bswap64
#define AV_WL64 av_write_bswap64

#else
#define AV_RB16 av_read_bswap16
#define AV_WB16 av_write_bswap16
#define AV_RB32 av_read_bswap32
#define AV_WB32 av_write_bswap32
#define AV_RB64 av_read_bswap64
#define AV_WB64 av_write_bswap64

#endif

static av_always_inline uint16_t av_read_bswap16(const void *p)
{
    uint16_t v;
    __asm__ ("lhbrx   %0, %y1" : "=r"(v) : "Z"(*(const uint16_t*)p));
    return v;
}

static av_always_inline void av_write_bswap16(void *p, uint16_t v)
{
    __asm__ ("sthbrx  %1, %y0" : "=Z"(*(uint16_t*)p) : "r"(v));
}

static av_always_inline uint32_t av_read_bswap32(const void *p)
{
    uint32_t v;
    __asm__ ("lwbrx   %0, %y1" : "=r"(v) : "Z"(*(const uint32_t*)p));
    return v;
}

static av_always_inline void av_write_bswap32(void *p, uint32_t v)
{
    __asm__ ("stwbrx  %1, %y0" : "=Z"(*(uint32_t*)p) : "r"(v));
}
```
Is it ok to be used as example to rearrange macros?

**Comment by crystalct** [comment]
Or use ppu_intrinsics.h and its macros? (solution good for PSL1GHT version and the other sdk, too)

**Pull request closed without merging**
