### PR TITLE
Rebase to latest git upstream

### PR DESCRIPTION
**Pull request by twinaphex**
Took a while to rebase it. I think I managed to successfully sync everything that was on the libretro repo (RetroAchievements memory maps, input bitmask support, turbo buttons, the extra colorization options by @jdgleaver, etc) while still being able to cleanly rebase from upstream.

I'd like to invite you @jdgleaver, @Ryunam, @negativeExponent and @Jamiras to test this. I'd like to ask @negativeExponent and @Jamiras in particular to test the RetroAchievements stuff, @Ryunam to ensure runahead is still working well, and @jdgleaver to confirm if all the features he added still work as expected.

### CODE REVIEW

**Review by endrift — CHANGES_REQUESTED** [review]
Sorry for the delay on this; I got caught up with some major bugs in 0.9.0 and was going to wait on 0.9.1 before doing this, though most of those bugs are already fixed in master.

I'd like to review the libretro.c changes to make sure things got merged properly, but as it stands the file got inexplicably re-linted, and extremely poorly at that, for no apparent good reason, so I cannot properly review it until the lint disaster is reverted. Regardless of code review it'll make future merges needlessly difficult if it's not reverted anyway.

image

**Comment by twinaphex** [comment]
@endrift Unfortunately that is the libretro code formatting we use for RetroArch and other libretro files. It's basically three spaces for a tab, and the other changes are general stylistic nits that we prefer. It only affects the libretro file that is in the libretro platform folder.

**Comment by endrift** [comment]
That doesn't explain the mixing of tabs and spaces. Don't reindent in the merge commit, either, as that obfuscates the process.

**Comment by twinaphex** [comment]
There is no mixing of tabs and spaces, no tabs are being used at all with this code formatting we use. Tabs get converted into three spaces. If there are any tabs remaining that would ideally be removed altogether so that the entire thing is consistent to the formatting. 

Anyway, I really don't care about this part - if you'd like you can just re-lint this however you prefer. Feel free to overwrite it as long as the rest of the code remains intact as it is.

**Comment by endrift** [comment]
There is clearly mixing of tabs and spaces in the screenshot I posted. I don't know how you missed that.

**Comment by twinaphex** [comment]
I pushed a change that should change the formatting of the file to use tabs for indentation. Hopefully this is satisfactory and we acn move on from this to the more substantive parts of this PR. In the interests of transparency, these are the Vim rules I used for this: :set noet ci pi sts=0 sw=4 ts=4

**Review by endrift — APPROVED** [review]

**Comment by endrift** [comment]
Alright. cleaned it up. Took a while but the diff is now legible and looks fine to me. I also removed the now-redundant e-Reader overrides since having two would break things.

Getting testing in before merging is a good idea.

I'm not opposed to reformatting the libretro.c file, especially since it seems to have some hodgepodge of at least three styles in it at the moment, but this PR was the wrong time to do it.

**Comment by twinaphex** [comment]
Yeah, I wholeheartedly agree. Thanks for going through the effort.

We will be awaiting feedback now from the people mentioned in the PR - we need to know if RetroAchievements support still works, if runahead works reliably (and performance is still good), etc.

**Comment by Sanaki** [comment]
I'm seeing a memory exposure issue for achievements. Found the issue using Kirby's Star Stacker. I'm not certain exactly what the memory being shown in the relevant region is, but it isn't what's expected and differs significantly from all other cores as well as the current master. Addresses in use for the achievement in question are `0x00bc3e` and `0x00bc05`, awarded for clearing normal difficulty of Round Clear mode (approximately a minute of minimal effort).

I'm still testing others games, but in general GB, GBC, and GBA achievements all seem to be popping fine. I'm guessing the issue may be SRAM-specific.

**Comment by jdgleaver** [comment]
`libretro.c` looks good to me, and all regular libretro functionality (apart from the aforementioned memory map) seems to work fine.

There is however a regression - Game Boy Color games will no longer load if `Skip BIOS Intro` is enabled (when using a real bios file). The games get stuck in a boot loop, displaying this:

Wario Land II (USA, Europe) (SGB Enhanced) (GBC)-210413-161857

**Comment by Ryunam** [comment]
First of all, huge thanks both to @endrift for the mGBA update and to @twinaphex for working on the libretro rebase. 

I am happy to report that, after building the core with Mingw64 and testing this new PR for a hour on my Windows system, Runahead seems to work very well. It appears to function smoothly and reliably just like before, with all the games I have tried.

Here is a few of the games I've tested:

- Castlevania Akatsuki no Minuet (Aria of Sorrow)
- Castlevania Byakuya no Concerto (Harmony of Dissonance)
- Final Fantasy IV Advance
- Kirby and the Amazing Mirror
- Metroid Fusion
- Metroid Zero Mission
- Mother 3 (Japanese version with the Fan-translation patch)
- Rockman Zero
- Sonic Advance

**Comment by Jamiras** [comment]
> I'm seeing a memory exposure issue for achievements. Found the issue using Kirby's Star Stacker. I'm not certain exactly what the memory being shown in the relevant region is, but it isn't what's expected and differs significantly from all other cores as well as the current master. Addresses in use for the achievement in question are `0x00bc3e` and `0x00bc05`, awarded for clearing normal difficulty of Round Clear mode (approximately a minute of minimal effort).

When I try to run Kirby's Star Stacker in RALibretro, I get memory access errors trying to read from the SRAM region. The memory associated to the pointer provided by the `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` appears to have been free'd at some point between calling `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` and the achievement code trying to use it.  I suspect you're just seeing whatever random memory happens to be in the space after it was free'd.

I don't see the problem with Final Fantasy Adventure (another GB title that has SRAM) or Super Mario Advance (GBA title with SRAM).

**Comment by endrift** [comment]
> Addresses in use for the achievement in question are `0x00bc3e` and `0x00bc05`, awarded for clearing normal difficulty of Round Clear mode (approximately a minute of minimal effort).

Those aren't valid memory addresses on the GBA, so I'm kind of curious how that was supposed to work at all.

**Comment by Jamiras** [comment]
> Those aren't valid memory addresses on the GBA, so I'm kind of curious how that was supposed to work at all.

Achievement addresses don't map 1:1 with hardware addresses. But in this particular case, the game is GB, not GBA, and those do addresses do actually map to the cartridge memory (SRAM).

**Comment by endrift** [comment]
@Jamiras I see. Can you check if calling `_setupMaps` in `_doDeferredSetup` fixes it?

**Comment by Jamiras** [comment]
That does update the memory map with the correct pointer, but the achievement code still references the old one because it's not notified of the change, so it doesn't prevent the error.

**Comment by endrift** [comment]
That sounds like an issue with the achievement code. What happens if the underlying system has to shuffle things around?

**Comment by Jamiras** [comment]
It hasn't been a problem before now. I agree that if `RETRO_SET_MEMORY_MAPS` is called while the game is running, the achievement code should adapt. I'm just pointing out that currently it doesn't. There's nothing in the `RETRO_SET_MEMORY_MAPS` handler that calls the achievement code to update the references.

**Comment by endrift** [comment]
Alright, well, I'll see what I can do. The deferred setup is an unfortunate necessity due to libretro API limitations, so the SRAM isn't set up by the time that function is called. That said, I don't know why the pointer would _change_ unless the original pointer is null?

**Comment by endrift** [comment]
The GBC BIOS skipping that @jdgleaver noted is fixed now, though I'm not 100% sure what to do about the memory map issue. The initial calls could be moved into deferredSetup, but I don't know if that would break things? It doesn't get done until the first time `retro_run` is called. @Jamiras

**Comment by Jamiras** [comment]
Yep. That works.

Changed
```
if (gb->memory.sram) {
    descs[i].ptr    = gb->memory.sram;
```

to
```
if (savedataSize) {
    descs[i].ptr    = savedata;
```

**Comment by endrift** [comment]
Pushed that fix. Unless more issues are found this should be good to go. I'm doing a bit of cleanup upstream at the moment to include some of the things that were overlooked when I was upstreaming stuff before (notably bitmasks atm)

**Comment by jdgleaver** [comment]
@endrift Thank you for fixing the GB skip bios issue - much appreciated!

**Comment by twinaphex** [comment]
I will merge it 8 hours from now if no other issues have been found by then. Hope everyone is OK with that, if not, let me know.

**Review by Jamiras — APPROVED** [review]
From an achievements standpoint, everything seems to be working now.

**Pull request merged**
