### PR TITLE
Update to mgba 0.8.1

### PR DESCRIPTION
**Pull request by RobLoach**
https://mgba.io/2020/02/16/mgba-0.8.1/

Great release, as always.

### CODE REVIEW

**Comment by endrift** [comment]
Libretro branch is currently tracking master. Merging this might be a bad idea and cause complications down the line. Again.

**Comment by RobLoach** [comment]
Oof, that's messy. It seems to reference 0.8.1 in version.cmake.
https://github.com/libretro/mgba/blob/master/version.cmake

That's probably from before you switched it to state 0.9 in https://github.com/mgba-emu/mgba/commit/7fb5d7006e215a8bab770fb05bc7022a01bef48b .

I can switch this to grab from `master` instead. Thanks a lot for the insight here.

**Comment by endrift** [comment]
Looking back, I might be mistaken. It seems I intentionally merged in 0.8. I can take another look in the morning to see if I can figure out what I did, but it's getting late here and I'm a little too tired to try and figure this out.

**Comment by RobLoach** [comment]
I'll push up a different Pull Request with 0.9 `master` so we can check the diff. Thanks for checking in!

**Comment by RobLoach** [comment]
The failure is clang, and likely can be ignored:
https://travis-ci.org/libretro/mgba/jobs/651344077?utm_medium=notification&utm_source=github_status

**Pull request merged**
