### PR TITLE
support for iOS arm64 build

### PR DESCRIPTION
**Pull request by yoshisuga**

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
Why "#include <mgba/internal/gba/bios.h>" in libretro.c? It can build fine here on Linux and other platforms as well

**Comment by yoshisuga** [comment]
When compiling for iOS arm64, getting this error:

```
src/platform/libretro/libretro.c:679:18: error: implicit declaration of function '_mLOG_CAT_GBA_BIOS' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (category == _mLOG_CAT_GBA_BIOS()) {
                        ^
src/platform/libretro/libretro.c:679:18: note: did you mean '_mLOG_CAT_GBA_SIO'?
clang: warning: argument unused during compilation: '-mno-thumb' [-Wunused-command-line-argument]
./include/mgba/internal/gba/sio.h:20:1: note: '_mLOG_CAT_GBA_SIO' declared here
mLOG_DECLARE_CATEGORY(GBA_SIO);
^
./include/mgba/core/log.h:58:45: note: expanded from macro 'mLOG_DECLARE_CATEGORY'
#define mLOG_DECLARE_CATEGORY(CATEGORY) int _mLOG_CAT_ ## CATEGORY (void); extern const char* _mLOG_CAT_ ## CATEGORY ## _ID;
                                            ^
<scratch space>:21:1: note: expanded from here
_mLOG_CAT_GBA_SIO
^
1 warning and 1 error generated.
```

I'm not sure why only the arm64 build runs into this error, and I thought including the bios header would be harmless, but if you have a better suggestion, I'm all for that.

**Comment by endrift** [comment]
There is (now) a better solution. I can integrate it upstream sometime tonight and get @sergiobenrocha2 to cherry-pick it if you can wait.

**Comment by yoshisuga** [comment]
Great! Thanks, will keep an eye out!

**Comment by endrift** [comment]
Upstream patch: 10a5432df72a68bf178163954e2dafdc92f7a742

**Comment by sergiobenrocha2** [comment]
Cherry-picked that, thanks!
@yoshisuga see the last commit

**Pull request closed without merging**
