### PR TITLE
Update downstream

### PR DESCRIPTION
**Pull request by endrift**
Since no one else was doing it, here's an update. As a PR since you quietly removed my write access while I wasn't paying attention. Very smooth.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
hey, thanks for this.

I've been telling end-users who were interested in some recent upstream updates that we usually wait for you to give the go-ahead before syncing. Is that not the case? If not, I think we can probably get someone to sync against upstream with more regularity.

**Comment by endrift** [comment]
There's generally not great communication. I've been waiting until I released 0.10, but since it's been drifting for so long now I decided to do it shortly before releasing 0.10.

**Comment by hizzlekizzle** [comment]
We appreciate it, certainly :)

It looks like the 3DS build is choking on the VFS a bit. Got any ideas there? https://git.libretro.com/libretro/mgba/-/jobs/2284671

**Comment by endrift** [comment]
The `_3DS` define has been replaced by `__3DS__` in devkitARM but the libretro Makefile didn't get updated to reflect that.

**Comment by hizzlekizzle** [comment]
womp womp, good catch. Thanks!

**Pull request merged**
