### PR TITLE
Add optional colour correction

### PR DESCRIPTION
**Pull request by jdgleaver**
This PR adds optional colour correction, based upon Pokefan531's latest shader pack: https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/174

It adds a new core option `Color Correction`, with four settings;

- `OFF`

- `GBA`: Force GBA colour correction

- `GBC`: Force GBC colour correction

- `Auto`: Apply GBA colour correction when running GBA titles, GBC colour correction when running GBC titles, and disable colour correction for GB/SGB content (i.e. always do the correct thing!)

Here are some examples:

- `Color Correction`: `OFF`

Shantae (USA) (GBC)-190613-141951

- `Color Correction`: `Auto`

Shantae (USA) (GBC)-190613-142002

- `Color Correction`: `OFF`

Wario Land II (USA, Europe) (SGB Enhanced) (GBC)-190613-142202

- `Color Correction`: `Auto`

Wario Land II (USA, Europe) (SGB Enhanced) (GBC)-190613-142212

- `Color Correction`: `OFF`

Golden Sun (USA, Europe)-190613-142422

- `Color Correction`: `Auto`

Golden Sun (USA, Europe)-190613-142431

- `Color Correction`: `OFF`

Wario Land 4 (USA, Europe)-190613-142334

- `Color Correction`: `Auto`

Wario Land 4 (USA, Europe)-190613-142355

Notes:

- This is done purely as a post-processing stage inside `libretro.c` - i.e. it doesn't interfere with any upstream code that would affect the stand-alone versions.

- It's implemented using a big old look-up table. This is wasteful of RAM (~128 kb) and requires a setup stage (~100 ms), but it means that the actual real-time colour conversion has a very small performance impact. (Also, when colour correction is disabled, no extra resources are used)

- While GBC colour correction is essentially perfect, rounding errors mean that internal GBA colour correction will never be as accurate as when using the `gba-color.glsl` GPU shader. However: most users shouldn't notice the difference, and even these (slightly) inaccurate results look great, and are an order of magnitude better than uncorrected colours. Moreover, this feature predominantly targets platforms without shader support (such as the Wii), where playing GBA titles is currently a rather oversaturated/garish experience.

### CODE REVIEW

**Comment by fr500** [comment]
does upstream have color correction?
if it does wouldn't it be better to tap into that?

**Comment by twinaphex** [comment]
It's reasonably self contained in libretro.c so it's not like this touches any surface area in the upstream core emulator code, and in case upstream has it, it would have to be carefully weighed if this implementation is faster than it. Performance matters in libretro cores, whether they are upstream or not, especially for older consoles.

**Comment by rz5** [comment]
@fr500 - mGBA on desktop does have an OpenGL multipass shader pipeline, if that's what you mean?

**Comment by twinaphex** [comment]
@rz5 But what jdgleaver implemented here aren't shaders, and the likes of 3DS doesn't have pixel shader support anyway, neither does Wii.

**Comment by twinaphex** [comment]
I don't see anything that is in upstream that covers this, and even if there is, this is likely to be more performant.

So unless I see evidence to the contrary, I see no reason to further stall this PR. Merging it.

**Comment by endrift** [comment]
Why did you remove frameskip, but not the setting for frameskip?

**Comment by twinaphex** [comment]
@endrift Yeah that might be worthwhile to add back. I'll bring this to @jdgleaver's attention.

**Comment by jdgleaver** [comment]
@endrift I didn't remove frameskip :)

The frameskip config code was originally duplicated - I just removed the redundant copies. I didn't think it was worth mentioning in the PR comment, since it was only a bit of housekeeping.

If you look at master, you'll see that frameskip is still present and correct:

https://github.com/libretro/mgba/blob/525d6538b036a38e3c744e10afd73c3910cdbe61/src/platform/libretro/libretro.c#L367-L371

https://github.com/libretro/mgba/blob/525d6538b036a38e3c744e10afd73c3910cdbe61/src/platform/libretro/libretro.c#L633-L638

**Comment by endrift** [comment]
Oh, huh, I wonder how it ended up getting duplicated.

**Pull request merged**
