### PR TITLE
Add android jni makefiles and fix libretro cmake support

### PR DESCRIPTION
**Pull request by webgeek1234**
This is mainly to help simplify the android buildbot recipes

### CODE REVIEW

**Comment by endrift** [comment]
Please sync the CMake changes with upstream changes first, they obviate a few of your changes.

**Comment by webgeek1234** [comment]
Alright, I'll close this and open a new one if needed after the upstream changes are pulled down.

**Comment by endrift** [comment]
I'll try and downstream stuff later today.

**Comment by twinaphex** [comment]
I'd say we go with this for now until the rebase happens. Users were complaining about the Android core not building so we need to fix this in the here and now.

**Pull request merged**
