### PR TITLE
Thin out fork

### PR DESCRIPTION
**Pull request by endrift**
This PR does several things:
- Merges current 0.6 branch
- Adds upstream support for building with GCC as far back as 4.0
- Has several PPC fixes
- Adds the localtime_r fix from #83 
- Thins out the fork now that GCC 4.0 is "supported", so out of date toolchains (cough PS3) should still work, also making merging easer in general

I didn't revert several libretro changes and didn't touch platform/libretro at all, so hopefully this won't be controversial. I can't confirm that it works on PS3 but I can confirm that it builds fine on PPC Mac (though oddly RetroArch doesn't appear to still have a PPC Mac build, despite twinaphex insisting that it should be supported as the original impetus for a bunch of the heavier-handed changes, so I couldn't test it) and works fine in RetroArch x86_64 Mac.

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
Working fine on x86_64 Linux (ubuntu 17.10)

**Comment by twinaphex** [comment]
> though oddly RetroArch doesn't appear to still have a PPC Mac build

Oh it does, but I just didn't add it for 1.6.9. I am about to release 1.7.0 though, and I will add a stable for PPC Mac again.

The main issue with the PPC releases is that we can't automate it yet through our buildbot, so I have to manually do it on my own computer.

**Comment by twinaphex** [comment]
@Clienthax try to test this out on your end when you have time and see if it works on RPCS3, and whether or not your original PR can be closed now as a result of this being merged.

**Comment by endrift** [comment]
Ah I see. I looked for any of the 1.6.x releases for PPC, but none were there. Moreover I couldn't seem to find archives beyond that, so I stopped looking.

**Comment by twinaphex** [comment]
Yeah, we are very close to releasing 1.7.0, so it will be back. If we had a toolchain we could install on our buildbot so we could automate this process, that'd be great, but so far we haven't found a suitable solution yet. It'd have to work on newer machines instead of old PPC OSX.

**Pull request merged**
