### PR TITLE
Update downstream to 0.10.0

### PR DESCRIPTION
**Pull request by Ryunam**
This PR brings downstream up to par with stable version 0.10.0, recently released. In my admittedly brief and limited testing on Windows, everything seems to be working well.

@endrift Please let me know if this is good to go, or else if there's anything that requires further attention.

### CODE REVIEW

**Comment by GABO1423** [comment]
Windows builds fail because the 'Makefile.libretro' file is still defined to use the C99 standard, whereas the code has been upgraded to C11.

**Comment by Ryunam** [comment]
I didn't spot this issue, due to the fact that compiling locally for Windows x64 through Msys2/Mingw64 just seemed to work normally and yield a usable core. 

Would replacing all occurrences of c99 with c11 in the libretro makefile suffice for this purpose?

**Comment by GABO1423** [comment]
> I didn't spot this issue, due to the fact that compiling locally for Windows x64 through Msys2/Mingw64 just seemed to work normally and yield a usable core.

Weirdly enough using msys2 on my computer just yielded build errors. Hence why I caught the issue. 

> Would replacing all occurrences of c99 with c11 in the libretro makefile suffice for this purpose?

Yes, that's exactly how I fixed the problem. But I don't know what effect would that have on other platforms.

**Comment by GaussTek** [comment]
Any update on this? I would love to have the latest version as a core :c

**Comment by hizzlekizzle** [comment]
@LibretroAdmin Can you create a new branch in the repo so we can merge this to the branch and run it through the CI to see if any/how many platforms break with c11?

**Comment by Ryunam** [comment]
In the meantime, I spoke to @GABO1423 over on Discord and, upon performing an update of their MSYS2/Mingw64 installation, everything went smoothly when compiling the core with this PR on Windows. Checking whether the CI shows any broken output definitely seems to be the most sensible choice.

**Comment by endrift** [comment]
> @endrift Please let me know if this is good to go, or else if there's anything that requires further attention.

Were there any merge conflicts in the process? I haven't looked too hard at this yet.

As for the C11 breakage, I might be able to provide some back-compat stuff, but C11 has been a standard for 11 years, so I'm not going to be putting too much effort into supporting an already-superseded-multiple-times version of C. I won't be switching to C17 anytime soon though.

**Comment by Ryunam** [comment]
No, luckily there were no merge conflicts with the commits that are currently included with this PR.

However, @GABO1423 pointed out on Discord that https://github.com/mgba-emu/mgba/commit/1cc32c0785b0838495658229c5143e3e5772330d (which is not included in this update) introduced a few build errors. Those seem to be fixable by adding the following lines to the `libretro-build/Makefile.common` file (around line 77):

```
$(CORE_DIR)/src/gb/mbc/huc-3.c \
$(CORE_DIR)/src/gb/mbc/licensed.c \
$(CORE_DIR)/src/gb/mbc/mbc.c \
$(CORE_DIR)/src/gb/mbc/pocket-cam.c \
$(CORE_DIR)/src/gb/mbc/tama5.c \
$(CORE_DIR)/src/gb/mbc/unlicensed.c \
```

Given that this update seems to be taking longer than expected due to the C99 compatibility concerns, I suggest we first address those and then work on the later commits (with all due fixes for the conflict mentioned above) with a separate PR later on.

**Pull request merged**
