### PR TITLE
Update downstream to 0.11-dev

### PR DESCRIPTION
**Pull request by Ryunam**
This PR brings the downstream libretro core up to par with version 0.11-dev. 
Credits go to @GABO1423 for the much appreciated suggestions on how to fix the compilation errors that came up after updating.

Tested briefly on Windows, everything seems to be working well.

### CODE REVIEW

**Comment by endrift** [comment]
This isn't 0.10.1. This is 0.11-dev.

**Comment by Ryunam** [comment]
Ok, in that case I would suggest two options:

- either we scrap this PR altogether, with the hopes that you may point me in the right direction for updating the downstream core to 0.10.1 proper;
- or I rework this PR to reflect the proper naming, changing the commit/PR name *and* the core version string in `retroarch.c` to 0.11-dev.

What do you prefer?

**Comment by endrift** [comment]
The latter will be easier, due to the merge conflicts that will arise when you try to update from 0.10.whatever to 0.11.0 when that comes out.

**Comment by Ryunam** [comment]
Should be all done. Unfortunately I couldn't find an easy way to rename the branch of my fork from 0.10.1 to 0.11-dev without force-closing this PR, but I suppose that's a negligible thing.

**Pull request merged**
